config/routes.rb
WorshipTuner::Application.routes.draw do
  resources :songs, :song_arrangements, :song_arrangement_files
  resources :blog_posts, path: 'blog' do
    get :dashboard, on: :collection
  end
  resources :blog_post_comments
  resources :blog_post_tags

  devise_for :users, path_names: { sign_up: 'register', sign_in: 'sign-in', sign_out: 'sign-out' }

  root to: 'static_pages#home'
  
  match '/how-it-works',  to: 'static_pages#how_it_works', as: '/how_it_works'
  match '/who-we-are',    to: 'static_pages#who_we_are', as: '/who_we_are'

  match '/contact',     to: 'contact#contact', via: :get
  match '/contact',     to: 'contact#contact_email', via: :post
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  # Accessible attributes for the BlogPost model.
  attr_accessible :title, :author, :body, :tag_list, :status
  
  # Associations for the BlogPost model.
  has_many :blog_post_comments, :dependent => :destroy
  has_many :blog_post_taggings, :dependent => :destroy
  has_many :blog_post_tags, through: :blog_post_taggings
  
  # Validations for the BlogPost model.
  validates :title, :author, :body, presence: true
  validates_length_of :title, maximum: 500
  validates_length_of :author, maximum: 250
  validates_length_of :body, maximum: 9000
  
  def self.tag_counts
  	BlogPostTag.select("blog_post_tags.*, COUNT(blog_post_taggings.blog_post_tag_id) AS count").joins(:blog_post_taggings).group("blog_post_taggings.blog_post_tag_id,blog_post_tags.id")
  end
  
  # Builds tag list for a given blog post
  def tag_list
  	return self.blog_post_tags.join(", ")
  end
  
  # Creates the tag_list virtual attribute
  def tag_list=(tags_string)
  	self.blog_post_taggings.destroy_all
  	
  	tag_names = tags_string.split(",").collect{ |s| s.strip }.uniq
  	
  	tag_names.each do |tag_name|
  	  blog_post_tag = BlogPostTag.find_or_create_by_name(tag_name)
  	  blog_post_tagging = self.blog_post_taggings.new
  	  blog_post_tagging.blog_post_tag_id = blog_post_tag.id
  	end
  end

  # Method used for the live search on the index view.
  def self.search(search)
    if search
      where('title ILIKE ? OR body ILIKE ?', "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  # Verifies that the user is singed in.
  before_filter :authenticate_user_is_admin, except: [ :show, :index ]
  
  # Gets a list of all blog posts.
  def index
    @blog_posts = BlogPost.search(params[:search]).paginate(page: params[:page], per_page: 5, conditions: ["status = ?", "1"], order: "created_at DESC, title DESC")
    @popular_blog_posts = BlogPost.find(:all, select: "blog_posts.*, COUNT(blog_post_comments.id) AS number_of_comments", joins: :blog_post_comments, group: "blog_posts.id", order: "number_of_comments DESC")
    @recent_blog_posts = BlogPost.find(:all, limit: 5, order: "created_at DESC")
  end
  
  # Display all blog posts (draft and live posts) as well as label counts and other dashboard items.
  def dashboard
    @blog_posts = BlogPost.search(params[:search]).paginate(page: params[:page], per_page: 20, order: "created_at DESC, title DESC")
  end
  
  # Gets a speific blog post.
  def show
    @blog_post = BlogPost.find(params[:id])
    @blog_post_comment = BlogPostComment.new
    @blog_post_comments = BlogPostComment.paginate(page: params[:page], per_page: 10, conditions: ["blog_post_id = ?", params[:id]], order: "created_at DESC, id DESC")
  end
  
  # Builds a new blog post object.
  def new
    @blog_post = BlogPost.new
  end
  
  # Saves the blog post object to the database.
  def create
    @blog_post = BlogPost.new(params[:blog_post])
    if @blog_post.save
      flash[:success] = "\"#{@blog_post.title}\" song has been successfully published to your blog."
      redirect_to blog_post_path(@blog_post)
    else
      render 'new'
    end
  end
  
  # Gets the blog post that has been requested for editing.
  def edit
    @blog_post = BlogPost.find(params[:id])
  end
  
  # Saves the updated blog post object to the database.
  def update
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.update_attributes(params[:blog_post])
      flash[:success] = "\"#{@blog_post.title}\" post has been updated."
      redirect_to blog_post_path(@blog_post)
    else
      render 'edit'
    end
  end
  
  # Deletes the specified blog post from the database.
  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    flash[:success] = "\"#{@blog_post.title}\" post has been deleted."
    redirect_to dashboard_blog_posts_path
  end
  
  private

    def authenticate_user_is_admin
      (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.try(:admin?))
    end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
  # Create tag links
  def tag_links(tags)
  	links = tags.order("name ASC").collect{ |tag| link_to tag.name, blog_post_tag_path(tag) }
  	return links.join(", ").html_safe
  end
  
  # Sets up the blog tag cloud
  def tag_cloud(tags, classes)
  	max = 0
  	tags.each do |t|
  	  if t.count.to_i > max
  	  	max = t.count.to_i
  	  end
  	end
  	tags.each do |tag|
  	  index = tag.count.to_f / max * (classes.size - 1)
  	  yield(tag, classes[index.round])
  	end
  end
end

app/views/blog_posts/_posts.html.erb
<%= will_paginate %>
	<section class="blog-posts">
		<% @blog_posts.each do |post| %>
			<article class="post">
				<section class="post-meta-info">
					<div class="post-title">
						<%= link_to "#{post.title}", post %>
						<% if current_user.try(:admin?) %>	
							<div class="post-actions">
								<%= link_to image_tag("icon_edit.png"), edit_blog_post_path(post), title: "Edit Post" %>
								<%= link_to image_tag("icon_delete.png"), post, method: :delete, data: { confirm: "Are you sure you want to delete the post: #{post.title} (by #{post.author})?" }, title: "Delete Post" %>
							</div>
						<% end %>
					</div>
					<div class="post-author">
						Posted by <%= post.author %>
					</div>
					<div class="post-date">
						Posted <%= time_ago_in_words(post.created_at) %> ago
					</div>
				</section>
				<section class="post-body-content">
					<div class="post-body">
						<%= post.body.html_safe %>
					</div>
					<div class="post-labels">
						<strong>Tags:</strong> <%= tag_links(post.blog_post_tags) %>
					</div>
				</section>
			</article>
		<% end %>
	</section>
<%= will_paginate %>

app/views/blog_posts/_posts_dashboard.html.erb
<%= will_paginate %>
	<section class="data-list">
		<% @blog_posts.each do |post| %>
			<article>
				<section class="data">
					<div class="data-title">
						<%= link_to "#{post.title}", post %>
						<div class="data-subtitle">
							Status: <%= (post.status == 1) ? 'Live' : 'Draft' %>
						</div>
					</div>
					<div class="data-note">
						Posted <%= time_ago_in_words(post.created_at) %> ago by <%= post.author %>
					</div>
				</section>
				<% if user_signed_in? %>
					<section class="data-actions">
						<%= link_to "Update", edit_blog_post_path(post), class: "btn btn-large btn-primary" %>
						<% if current_user.try(:admin?) %>					
							<%= link_to "Delete", post, method: :delete, data: { confirm: "Are you sure you want to delete the post: #{post.title} (by #{post.author})?" }, class: "btn btn-large" %>
						<% end %>
					</section>
				<% end %>
			</article>
		<% end %>
	</section>
<%= will_paginate %>

app/views/blog_posts/dashboard.html.erb
<% provide(:title, 'Blog Dashboard') %>

<h1>Dashboard</h1>

<% if @blog_posts.empty? %>
	<h2>No blog posts have been posted yet.</h2>
<% else %>
	<%= form_tag dashboard_blog_posts_path, :method => 'get', id: "blog_posts_search" do %>
		<%= label_tag :search, "Search Blog Posts" %>
		<%= text_field_tag :search, params[:search], class: "input-xxlarge" %>
	<% end %>
	
	<div id="blog_posts_dashboard">
		<%= render 'posts_dashboard' %>
	</div>
<% end %>
<%= link_to "New Post", new_blog_post_path, class: "btn btn-large btn-primary btn-add-new" %>

app/views/blog_posts/dashboard.js.erb
$("#blog_posts_dashboard").html("<%= escape_javascript(render("posts_dashboard")) %>");

app/views/blog_posts/edit.html.erb
<%= tinymce theme_advanced_buttons1: "bold,italic,underline,strikethrough,separator,forecolor,separator,bullist,numlist,outdent,indent,separator,undo,redo,separator,removeformat,code,fullscreen", theme_advanced_buttons2: "", theme_advanced_buttons3: "", width: "100%", height: "600", content_css: "/assets/tinymce.css", valid_elements: "-strong,-em,-u,-p,p[style],-ol,ol[style],-ul,ul[style],-li,li[style],-span,span[style],-div,div[style]", theme_advanced_resizing: true, theme_advanced_resize_horizontal: false %>

<%= provide(:title, "Update Post: #{@blog_post.title}") %>

<h1>Update Post: <%= @blog_post.title %></h1>

<%= form_for(@blog_post) do |f| %>
	<%= render 'shared/error_messages', :object => @blog_post %>
	
	<%= f.label :title, "Post Title*" %>
	<%= f.text_field :title, placeholder: "Enter the title of the post...", class: "input-xxlarge" %>
	
	<%= f.label :body, "Post Content*" %>
	<%= f.text_area :body, class: "tinymce" %>
	
	<%= f.label :tag_list, "Tags (separate by commas)" %>
    <%= f.text_field :tag_list, placeholder: "Enter tags for this post...", class: "input-xxlarge" %>
	
	<%= f.label :status, "Status?" %>
	<%= f.radio_button :status, 0 %> Draft<br />
	<%= f.radio_button :status, 1 %> Live
	
	<div>
		<%= f.submit "Publish", class: "btn btn-large btn-primary" %>
		<div class="disclaimer">*required field</div>
	</div>
<% end %>

app/views/blog_posts/index.html.erb
<% provide(:title, 'Blog') %>

<h1>Blog</h1>

<% if @blog_posts.empty? %>
	<h2>No blog posts have been posted yet.</h2>
<% else %>
	<section class="blog-roll">
		<%= form_tag blog_posts_path, :method => 'get', id: "blog_posts_search" do %>
			<%= label_tag :search, "Search Blog Posts" %>
			<%= text_field_tag :search, params[:search], class: "input-xxlarge" %>
		<% end %>
		
		<div id="blog_posts">
			<%= render 'posts' %>
		</div>
	</section>
	<section class="blog-sidebar">
		<div class="blog-tag-cloud">
			<h4>Tag Cloud</h4>
			<% tag_cloud BlogPost.tag_counts, %w[rare, somewhat frequent] do |tag, css_class| %>
				<%= link_to tag.name, blog_post_tag_path(tag.name), class: css_class %>
			<% end %>
		</div>
		<div class="popular-blog-posts">
			<h4>Most Popular Posts</h4>
			<% @popular_blog_posts.each do |post| %>
				<div class="blog-post-title">
					<%= link_to post.title, blog_post_path(post) %>
				</div>
			<% end %>
		</div>
		<div class="recent-blog-posts">
			<h4>Recent Posts</h4>
			<% @recent_blog_posts.each do |post| %>
				<div class="blog-post-title">
					<%= link_to post.title, blog_post_path(post) %>
				</div>
			<% end %>
		</div>
	</section>
	<div class="cleanup"></div>
<% end %>

app/views/blog_posts/index.js.erb
$("#blog_posts").html("<%= escape_javascript(render("posts")) %>");

app/views/blog_posts/new.html.erb
<%= tinymce theme_advanced_buttons1: "bold,italic,underline,strikethrough,separator,forecolor,separator,bullist,numlist,outdent,indent,separator,undo,redo,separator,removeformat,code,fullscreen", theme_advanced_buttons2: "", theme_advanced_buttons3: "", width: "100%", height: "600", content_css: "/assets/tinymce.css", valid_elements: "-strong,-em,-u,-p,p[style],-ol,ol[style],-ul,ul[style],-li,li[style],-span,span[style],-div,div[style]", theme_advanced_resizing: true, theme_advanced_resize_horizontal: false %>

<%= provide(:title, 'Add New Post') %>

<h1>Add New Post</h1>

<%= form_for(@blog_post) do |f| %>
	<%= render 'shared/error_messages', :object => @blog_post %>
	
	<%= f.label :title, "Post Title*" %>
	<%= f.text_field :title, placeholder: "Enter the title of the post...", class: "input-xxlarge" %>
	
	<%= f.label :body, "Post Content*" %>
	<%= f.text_area :body, class: "tinymce" %>
	
	<%= f.label :tag_list, "Tags (separate by commas)" %>
    <%= f.text_field :tag_list, placeholder: "Enter tags for this post...", class: "input-xxlarge" %>
	
	<%= f.label :status, "Status?" %>
	<%= f.radio_button :status, 0 %> Draft<br />
	<%= f.radio_button :status, 1 %> Live
	
	<%= f.hidden_field :author, value: "#{current_user.name}" %>
	
	<div>
		<%= f.submit "Publish", class: "btn btn-large btn-primary" %>
		<div class="disclaimer">*required field</div>
	</div>
<% end %>

app/views/blog_posts/show.html.erb
<% provide(:title, "#{@blog_post.title}") %>

<section class="post-content">
	<div class="post-title">
		<%= @blog_post.title %>
		<% if current_user.try(:admin?) %>	
			<div class="post-actions">
				<%= link_to image_tag("icon_edit.png"), edit_blog_post_path(@blog_post), title: "Edit Post" %>
				<%= link_to image_tag("icon_delete.png"), @blog_post, method: :delete, data: { confirm: "Are you sure you want to delete the post: #{@blog_post.title} (by #{@blog_post.author})?" }, title: "Delete Post" %>
			</div>
		<% end %>
	</div>
	<div class="post-author">
		Posted by <%= @blog_post.author %>
	</div>
	<div class="post-date">
		Posted <%= time_ago_in_words(@blog_post.created_at) %> ago
	</div>
	<div class="post-body">
		<%= @blog_post.body.html_safe %>
	</div>
	<div class="post-labels">
		<strong>Tags:</strong> <%= tag_links(@blog_post.blog_post_tags) %>
	</div>
</section>
<section class="post-comments">
	<h2><%= pluralize(@blog_post_comments.size, "Comment") %></h2>
	<% if @blog_post_comments.empty? %>
		<h4>No one has commented on this post yet.</h4>
	<% end %>
	<%= will_paginate @blog_post_comments %>
		<section class="comments-list">
			<% @blog_post_comments.each do |comment| %>
				<article class="comment">
					<div class="comment-author">
						<%= gravatar_for comment, size: 40 %>&nbsp; <%= comment.name %> <span class="comment-date">commented <%= time_ago_in_words(comment.created_at) %> ago</span>
						<% if current_user.try(:admin?) || (user_signed_in? && current_user.email == comment.email) %>
							<div class="post-actions">
								<%= link_to image_tag("icon_delete.png"), comment, method: :delete, data: { confirm: "Are you sure you want to delete this comment?" }, title: "Delete Comment" %>
							</div>
						<% end %>
					</div>
					<div class="comment-body">
						<%= comment.comment %>
					</div>
				</article>
			<% end %>
		</section>
	<%= will_paginate @blog_post_comments %>
	<%= form_for(@blog_post_comment) do |f| %>
		<h3>Add New Comment</h3>
		
		<%= render 'shared/error_messages', :object => @blog_post_comment %>
		
		<% if user_signed_in? %>
			<%= gravatar_for current_user, size: 40 %>&nbsp; <span class="user-name"><%= current_user.name %></span>
			<%= f.hidden_field :name, value: "#{current_user.name}" %>
			<%= f.hidden_field :email, value: "#{current_user.email}" %>
		<% else %>
			<%= f.label :name, "Name*" %>
			<%= f.text_field :name, placeholder: "Enter your name...", class: "input-xxlarge" %>
			<%= f.label :email, "Email" %>
			<%= f.text_field :email, placeholder: "Enter your email...", class: "input-xxlarge" %>
		<% end %>
		
		<%= f.label :comment, "Comment*" %>
		<%= f.text_area :comment, placeholder: "Enter your comment..." %>

		<%= f.hidden_field :blog_post_id, value: "#{@blog_post.id}" %>
		
		<div>
			<%= f.submit "Publish", class: "btn btn-large btn-primary" %>
			<div class="disclaimer">*required fields</div>
		</div>
	<% end %>
</section>