config/routes.rb
WorshipTuner::Application.routes.draw do
  resources :songs, :song_arrangements, :song_arrangement_files
  resources :blog_posts, path: 'blog' do
    get :dashboard, on: :collection
  end
  resources :blog_post_comments
  resources :blog_post_tags

  devise_for :users, path_names: { sign_up: 'register', sign_in: 'sign-in', sign_out: 'sign-out' }

  root to: 'static_pages#home'
  
  match '/how-it-works',  to: 'static_pages#how_it_works', as: '/how_it_works'
  match '/who-we-are',    to: 'static_pages#who_we_are', as: '/who_we_are'

  match '/contact',     to: 'contact#contact', via: :get
  match '/contact',     to: 'contact#contact_email', via: :post
end

app/models/song.rb
class Song < ActiveRecord::Base
  # Accessible attributes for the Song model.
  attr_accessible :title, :artist, :added_by, :updated_by
  
  # Associations for the Song model.
  has_many :song_arrangements, :dependent => :destroy
  has_many :song_arrangement_files, :through => :song_arrangements
  
  # Validations for the Song model.
  validates :title, :artist, presence: true
  validates_length_of :title, :artist, maximum: 500
  validates :title, uniqueness: { scope: :artist, message: "has already been created for this artist." }
  
  # Method used for the live search on the index view.
  def self.search(search)
    if search
      where('title ILIKE ? OR artist ILIKE ?', "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # Verifies that the user is singed in.
  before_filter :authenticate_user!, except: [ :index, :show ]
  before_filter :authenticate_user_is_admin, only: :destroy
  
  # Gets a list of all song arrangement files.
  def index
     @songs = Song.search(params[:search]).paginate(page: params[:page], per_page: 20, order: "title ASC, artist ASC")
  end

  # Gets a speific song.
  def show
    @song = Song.find(params[:id])
    @song_arrangements = SongArrangement.paginate(page: params[:page], per_page: 5, joins: "LEFT JOIN song_arrangement_files ON song_arrangement_files.song_id = song_arrangements.song_id", conditions: ["song_arrangements.song_id = ?", params[:id]], group: "song_arrangements.id", order: "song_arrangements.title ASC, song_arrangements.original_key ASC, song_arrangements.bpm ASC, song_arrangements.id ASC")
  end

  # Builds a new song object.
  def new
    @song = Song.new
  end

  # Saves the song object to the database.
  def create
    @song = Song.new(params[:song])
    if @song.save
      flash[:success] = "\"#{@song.title}\" song has been added to the song library."
      redirect_to edit_song_path(@song)
    else
      render 'new'
    end
  end

  # Gets the song that has been requested for editing.
  def edit
    @song = Song.find(params[:id])
    @song_arrangements = SongArrangement.paginate(page: params[:page], per_page: 10, conditions: ["song_id = ?", params[:id]], order: "title ASC, original_key ASC, bpm ASC, id ASC")
  end

  # Saves the updated song object to the database.
  def update
    @song = Song.find(params[:id])
    if @song.update_attributes(params[:song])
      flash[:success] = "\"#{@song.title}\" song has been updated."
      redirect_to :back
    else
      render 'edit'
    end
  end

  # Deletes the specified song from the database.
  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    flash[:success] = "\"#{@song.title}\" song has been deleted."
    redirect_to songs_path
  end
  
  private

    def authenticate_user_is_admin
      (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.try(:admin?))
    end
end

app/views/songs/_songs.html.erb
<%= will_paginate %>
	<section class="data-list">
		<% @songs.each do |song| %>
			<article>
				<section class="data">
					<div class="data-title">
						<%= link_to "#{song.title}", song %>
						<div class="data-subtitle">
							by <%= song.artist %>
						</div>
					</div>
				</section>
				<% if user_signed_in? %>
					<section class="data-actions">
						<%= link_to "Manage", edit_song_path(song), class: "btn btn-large btn-primary" %>
						<% if current_user.try(:admin?) %>					
							<%= link_to "Delete", song, method: :delete, data: { confirm: "Are you sure you want to delete the song: #{song.title} (by #{song.artist})?" }, class: "btn btn-large" %>
						<% end %>
					</section>
				<% end %>
			</article>
		<% end %>
	</section>
<%= will_paginate %>

app/views/songs/edit.html.erb
<%= provide(:title, "Manage Song: #{@song.title}") %>

<h1>Manage Song: <%= @song.title %></h1>

<%= form_for(@song) do |f| %>
	<%= render 'shared/error_messages', :object => @song %>
	
	<%= f.label :title, "Song Title*" %>
	<%= f.text_field :title, placeholder: "Enter the title of the song...", class: "input-xxlarge" %>
	
	<%= f.label :artist, "Song Artist*" %>
	<%= f.text_field :artist, placeholder: "Enter the artist of the song...", class: "input-xxlarge" %>
	
	<%= f.hidden_field :updated_by, value: "#{current_user.email}" %>
	
	<div>
		<%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
		<div class="disclaimer">*all fields required</div>
	</div>
<% end %>

<div class="song-arrangements">
	<% if @song_arrangements.empty? %>
		<h2>No arrangements have been added to this song.</h2>
	<% end %>
	
	<%= will_paginate @song_arrangements %>
		<section class="data-list">
			<% @song_arrangements.each do |arrangement| %>
				<article>
					<section class="data">
						<div class="data-title">
							<%= link_to "#{arrangement.title}", arrangement %>
							<div class="data-subtitle">
								Key: <%= arrangement.original_key %>
							</div>
						</div>
						<div class="data-note">
							<%= (arrangement.bpm == 0) ? "" : "#{arrangement.bpm} bpm" %>
						</div>
					</section>
					<section class="data-actions">
						<%= link_to "Manage", edit_song_arrangement_path(arrangement), class: "btn btn-large btn-primary" %>
						<% if current_user.try(:admin?) %>					
							<%= link_to "Delete", arrangement, method: :delete, data: { confirm: "Are you sure you want to delete the song arrangement: #{arrangement.title}?" }, class: "btn btn-large" %>
						<% end %>
					</section>
				</article>
			<% end %>
		</section>
	<%= will_paginate @song_arrangements %>

	<%= link_to "Add Arrangement", new_song_arrangement_path(song_id: @song.id), class: "btn btn-large btn-primary btn-add-new" %>
</div>

app/views/songs/index.html.erb
<% provide(:title, 'Song Library') %>

<h1>Song Library</h1>

<% if @songs.empty? %>
	<h2>There are no songs in this library.</h2>
<% else %>
	<%= form_tag songs_path, :method => 'get', id: "songs_search" do %>
		<%= label_tag :search, "Search Songs" %>
		<%= text_field_tag :search, params[:search], class: "input-xxlarge" %>
	<% end %>
	
	<div id="songs">
		<%= render 'songs' %>
	</div>
	
	<% if user_signed_in? %>
		<%= link_to "Add to Library", new_song_path, class: "btn btn-large btn-primary btn-add-new" %>
	<% end %>
<% end %>

app/views/songs/index.js.erb
$("#songs").html("<%= escape_javascript(render("songs")) %>");

app/views/songs/new.html.erb
<%= provide(:title, 'Add New Song') %>

<h1>Add New Song</h1>

<%= form_for(@song) do |f| %>
	<%= render 'shared/error_messages', :object => @song %>
	
	<%= f.label :title, "Song Title*" %>
	<%= f.text_field :title, placeholder: "Enter the title of the song...", class: "input-xxlarge" %>
	
	<%= f.label :artist, "Song Artist*" %>
	<%= f.text_field :artist, placeholder: "Enter the artist of the song...", class: "input-xxlarge" %>
	
	<%= f.hidden_field :added_by, value: "#{current_user.email}" %>
	
	<div>
		<%= f.submit "Add", class: "btn btn-large btn-primary" %>
		<div class="disclaimer">*all fields required</div>
	</div>
<% end %>

app/views/songs/show.html.erb
<% provide(:title, "#{@song.title}") %>

<h1><%= @song.title %></h1>
<h2>by <%= @song.artist %></h2>

<h3>Arrangements</h3>

<% if @song_arrangements.empty? %>
	<h4>No arrangements have been added to this song.</h4>
<% end %>

<%= will_paginate @song_arrangements %>
	<section class="song-arrangements-list">
		<% @song_arrangements.each do |arrangement| %>
			<article class="song-arrangement">
				<section class="arrangement-title-and-details">
					<span class="arrangement-title"><%= link_to "#{arrangement.title}", arrangement %></span>
					<span class="arrangement-details">[<%= arrangement.original_key %><%= (arrangement.bpm == 0) ? "" : "#{arrangement.bpm} bpm" %>]</span>
				</section>
				<section class="arrangement-attachments">
					<h4>Attachments</h4>
					<% if arrangement.song_arrangement_files.empty? %>
						<div class="no-attached-file">
							There are no attachments for this arrangement.
						</div>
					<% end %>
					<% arrangement.song_arrangement_files.each do |attachment| %>
						<% if !attachment.file_path.path %>
							<a class="attached-file" href="<%= attachment.url %>" target="_blank">
						<% else %>
							<a class="attached-file" href="<%= song_arrangement_file_path(attachment) %>">
						<% end %>
							File: <span class="link"><%= attachment.title %></span>
						</a>
					<% end %>
				</section>
			</article>
		<% end %>
	</section>
<%= will_paginate @song_arrangements %>