config/routes.rb
WorshipTuner::Application.routes.draw do
  resources :songs, :song_arrangements, :song_arrangement_files
  resources :blog_posts, path: 'blog' do
    get :dashboard, on: :collection
  end
  resources :blog_post_comments
  resources :blog_post_tags

  devise_for :users, path_names: { sign_up: 'register', sign_in: 'sign-in', sign_out: 'sign-out' }

  root to: 'static_pages#home'
  
  match '/how-it-works',  to: 'static_pages#how_it_works', as: '/how_it_works'
  match '/who-we-are',    to: 'static_pages#who_we_are', as: '/who_we_are'

  match '/contact',     to: 'contact#contact', via: :get
  match '/contact',     to: 'contact#contact_email', via: :post
end

app/models/song_arrangement.rb
class SongArrangement < ActiveRecord::Base
  # Accessible attributes for the SongArrangement model.
  attr_accessible :song_id, :title, :notes, :chart_content, :chart_mapping, :original_key, :bpm, :added_by, :updated_by
  
  # Associations for the SongArrangement model.
  belongs_to :song
  has_many :song_arrangement_files, :dependent => :destroy
  
  # Validations for the SongArrangement model.
  validates :title, :chart_content, presence: true
  validates_length_of :title, maximum: 500
  validates_length_of :original_key, maximum: 2
  validates_length_of :chart_mapping, maximum: 250
  validates_length_of :chart_content, :notes, maximum: 9000
  
  # Method used for the live search on the index view.
  def self.search(search)
    if search
      where('song_arrangements.title ILIKE ? OR songs.title ILIKE ?', "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/song_arrangements_controller.rb
class SongArrangementsController < ApplicationController
  # Verifies that the user is singed in.
  before_filter :authenticate_user!, except: :show
  before_filter :authenticate_user_is_admin, only: :destroy
  
  # Gets a list of all song arrangement files.
  def index
    @song_arrangements = SongArrangement.search(params[:search]).paginate(page: params[:page], per_page: 20, joins: :song, order: "song_arrangements.title ASC, songs.title ASC, song_arrangements.original_key ASC, song_arrangements.bpm ASC, song_arrangements.id ASC")
  end

  # Gets a speific song arrangement file.
  def show
    @song_arrangement = SongArrangement.find(params[:id], joins: :song)
    @song_arrangement_files = SongArrangementFile.find(:all, conditions: ["song_arrangement_id = ?", params[:id]], order: "title ASC, id ASC")
  end

  # Builds a new song arrangement file object.
  def new
    @song_arrangement = SongArrangement.new
    @song = Song.find(params[:song_id])
  end

  # Saves the song arrangement file object to the database.
  def create
    @song_arrangement = SongArrangement.new(params[:song_arrangement])
    @song = Song.find(params[:song_arrangement][:song_id])
    if @song_arrangement.save
      flash[:success] = "\"#{@song_arrangement.title}\" arrangement has been added to #{@song.title}."
      redirect_to edit_song_path(params[:song_arrangement][:song_id])
    else
      render 'new'
    end
  end

  # Gets the song arrangement file that has been requested for editing.
  def edit
    @song_arrangement = SongArrangement.find(params[:id], joins: :song)
    @song_arrangement_files = SongArrangementFile.paginate(page: params[:page], per_page: 10, conditions: ["song_arrangement_id = ?", params[:id]], order: "title ASC, id ASC")
  end

  # Saves the updated song arrangement file object to the database.
  def update
    @song_arrangement = SongArrangement.find(params[:id])
    if @song_arrangement.update_attributes(params[:song_arrangement])
      flash[:success] = "\"#{@song_arrangement.title}\" arrangement has been updated."
      redirect_to :back
    else
      render 'edit'
    end
  end

  # Deletes the specified song arrangement file from the database.
  def destroy
    @song_arrangement = SongArrangement.find(params[:id])
    @song_arrangement.destroy
    flash[:success] = "\"#{@song_arrangement.title}\" arrangement has been deleted."
    redirect_to :back
  end
  
  private

    def authenticate_user_is_admin
      (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.try(:admin?))
    end
end

app/views/song_arrangements/_song_arrangements.html.erb
<%= will_paginate %>
	<section class="data-list">
		<% @song_arrangements.each do |arrangement| %>
			<article>
				<section class="data">
					<div class="data-title">
						<%= link_to "#{arrangement.title}", arrangement %>
						<div class="data-subtitle">
							Song: <%= arrangement.song.title %>
						</div>
					</div>
					<div class="data-note">
						[<%= arrangement.original_key %><%= (arrangement.bpm == 0) ? "" : ", #{arrangement.bpm} bpm" %>]
					</div>
				</section>
				<section class="data-actions">
					<%= link_to "Manage", edit_song_arrangement_path(arrangement), class: "btn btn-large btn-primary" %>
					<% if current_user.try(:admin?) %>					
						<%= link_to "Delete", arrangement, method: :delete, data: { confirm: "Are you sure you want to delete the song arrangement: #{arrangement.title}?" }, class: "btn btn-large" %>
					<% end %>
				</section>
			</article>
		<% end %>
	</section>
<%= will_paginate %>

app/views/song_arrangements/edit.html.erb
<%= tinymce theme_advanced_buttons1: "bold,italic,underline,strikethrough,separator,forecolor,separator,bullist,numlist,outdent,indent,separator,undo,redo,separator,removeformat,code,fullscreen", theme_advanced_buttons2: "", theme_advanced_buttons3: "", width: "100%", height: "600", content_css: "/assets/tinymce.css", valid_elements: "-strong,-em,-u,-p,p[style],-ol,ol[style],-ul,ul[style],-li,li[style],-span,span[style],-div,div[style]", theme_advanced_resizing: true, theme_advanced_resize_horizontal: false %>

<%= provide(:title, "Update Arrangement: #{@song_arrangement.title}") %>

<h1>Update Arrangement: <%= @song_arrangement.title %></h1>
<h2>Arrangement for: <%= @song_arrangement.song.title %></h2>

<%= form_for(@song_arrangement) do |f| %>
	<%= render 'shared/error_messages', :object => @song_arrangement %>
	
	<%= f.label :title, "Arrangement Title*" %>
	<%= f.text_field :title, placeholder: "Enter the title of the arrangement...", class: "input-xxlarge" %>
	
	<%= f.label :original_key, "Original Key" %>
	<%= f.select :original_key, ["Ab", "A", "A#", "Bb", "B", "C", "C#", "Db", "D", "D#", "Eb", "E", "F", "F#", "Gb", "G", "G#"], class: "input-mini" %>
	
	<%= f.label :bpm, "BPM" %>
	<%= f.number_field :bpm, class: "input-mini" %>
	
	<%= f.label :chart_content, "Chart*" %>
	<%= f.text_area :chart_content, class: "tinymce" %>
	
	<%= f.label :chart_mapping, "Mapping" %>
	<%= f.text_field :chart_mapping, placeholder: "V1, C, V2, C, B, C, C", class: "input-xxlarge" %>
	
	<%= f.label :notes, "Notes" %>
	<%= f.text_area :notes, class: "tinymce" %>
	
	<%= f.hidden_field :updated_by, value: "#{current_user.email}" %>
	
	<div>
		<%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
		<div class="disclaimer">*required field</div>
	</div>
<% end %>

<div class="song-arrangement-files">
	<% if @song_arrangement_files.empty? %>
		<h2>No attachments have been uploaded for this song arrangement.</h2>
	<% end %>
	
	<%= will_paginate @song_arrangement_files %>
		<section class="data-list">
			<% @song_arrangement_files.each do |attachment| %>
				<article>
					<section class="data">
						<div class="data-title">
							<%= link_to "#{attachment.title}", attachment %>
						</div>
					</section>
					<section class="data-actions">
						<%= link_to "Manage", edit_song_arrangement_file_path(attachment), class: "btn btn-large btn-primary" %>
						<% if current_user.try(:admin?) %>					
							<%= link_to "Delete", attachment, method: :delete, data: { confirm: "Are you sure you want to delete the attachment: #{attachment.title}?" }, class: "btn btn-large" %>
						<% end %>
					</section>
				</article>
			<% end %>
		</section>
	<%= will_paginate @song_arrangement_files %>

	<%= link_to "Add Attachment", new_song_arrangement_file_path(song_id: @song_arrangement.song.id, song_arrangement_id: @song_arrangement.id), class: "btn btn-large btn-primary btn-add-new" %>
</div>

app/views/song_arrangements/index.html.erb
<% provide(:title, 'Arrangement Library') %>

<h1>Arrangement Library</h1>

<% if @song_arrangements.empty? %>
	<h2>There are no arrangements in this library.</h2>
<% else %>
	<%= form_tag song_arrangements_path, :method => 'get', id: "song_arrangements_search" do %>
		<%= label_tag :search, "Search Arrangements" %>
		<%= text_field_tag :search, params[:search], class: "input-xxlarge" %>
	<% end %>
	
	<div id="song_arrangements">
		<%= render 'song_arrangements' %>
	</div>
<% end %>

app/views/song_arrangements/index.js.erb
$("#song_arrangements").html("<%= escape_javascript(render("song_arrangements")) %>");

app/views/song_arrangements/new.html.erb
<%= tinymce theme_advanced_buttons1: "bold,italic,underline,strikethrough,separator,forecolor,separator,bullist,numlist,outdent,indent,separator,undo,redo,separator,removeformat,code,fullscreen", theme_advanced_buttons2: "", theme_advanced_buttons3: "", width: "100%", height: "600", content_css: "/assets/tinymce.css", valid_elements: "-strong,-em,-u,-p,p[style],-ol,ol[style],-ul,ul[style],-li,li[style],-span,span[style],-div,div[style]", theme_advanced_resizing: true, theme_advanced_resize_horizontal: false %>

<%= provide(:title, 'Add New Arrangement') %>

<h1>Add New Arrangement</h1>
<h2>Arrangement for: <%= @song.title %></h2>

<%= form_for(@song_arrangement) do |f| %>
	<%= render 'shared/error_messages', :object => @song_arrangement %>
	
	<%= f.label :title, "Arrangement Title*" %>
	<%= f.text_field :title, placeholder: "Enter the title of the arrangement...", class: "input-xxlarge" %>
	
	<%= f.label :original_key, "Original Key" %>
	<%= f.select :original_key, ["Ab", "A", "A#", "Bb", "B", "C", "C#", "Db", "D", "D#", "Eb", "E", "F", "F#", "Gb", "G", "G#"], class: "input-mini" %>
	
	<%= f.label :bpm, "BPM" %>
	<%= f.number_field :bpm, class: "input-mini" %>
	
	<%= f.label :chart_content, "Chart*" %>
	<%= f.text_area :chart_content, class: "tinymce" %>
	
	<%= f.label :chart_mapping, "Mapping" %>
	<%= f.text_field :chart_mapping, placeholder: "V1, C, V2, C, B, C, C", class: "input-xxlarge" %>
	
	<%= f.label :notes, "Notes" %>
	<%= f.text_area :notes, class: "tinymce" %>
	
	<%= f.hidden_field :added_by, value: "#{current_user.email}" %>
	<%= f.hidden_field :song_id, value: "#{@song.id}" %>
	
	<div>
		<%= f.submit "Add", class: "btn btn-large btn-primary" %>
		<div class="disclaimer">*required field</div>
	</div>
<% end %>

app/views/song_arrangements/show.html.erb
<%= provide(:title, "#{@song_arrangement.title}") %>

<section class="song-arrangement-wrapper">
	<%= link_to_function "Print this Page", "javascript:print()", class: "btn btn-small" %>
	<div class="song-arrangement-title">
		<h3><%= @song_arrangement.song.title %> [<%= @song_arrangement.original_key %><%= (@song_arrangement.bpm == 0) ? "" : ", #{@song_arrangement.bpm} bpm" %>]</h3>
		<h4><%= @song_arrangement.song.artist %></h4>
		<h4><%= @song_arrangement.chart_mapping %></h4>
	</div>
	<div class="song-arrangement-chart">
		<%= @song_arrangement.chart_content.html_safe %>
	</div>
</section>
<section class="song-arrangement-attached-files-and-notes-wrapper">
	<section class="song-arrangement-attached-files">
		<h4>Attachments</h4>
		<% if @song_arrangement_files.empty? %>
			<div class="no-attached-file">
				There are no attachments for this arrangement.
			</div>
		<% end %>
		<% @song_arrangement_files.each do |attachment| %>
			<% if !attachment.file_path.path %>
				<a class="attached-file" href="<%= attachment.url %>" target="_blank">
			<% else %>
				<a class="attached-file" href="<%= attachment.file_path %>" target="_blank">
			<% end %>
				File: <span class="link"><%= attachment.title %></span>
			</a>
		<% end %>
	</section>
	<section class="song-arrangement-notes">
		<h4>Notes</h4>
		<div class="arrangement-notes">
			<% if @song_arrangement.notes.empty? %>
				<p><strong>There are no notes for this arrangement.</strong></p>
			<% end %>
			<%= @song_arrangement.notes.html_safe %>
		</div>
	</section>
</section>
<div class="cleanup"></div>