config/routes.rb
WorshipTuner::Application.routes.draw do
  resources :songs, :song_arrangements, :song_arrangement_files
  resources :blog_posts, path: 'blog' do
    get :dashboard, on: :collection
  end
  resources :blog_post_comments
  resources :blog_post_tags

  devise_for :users, path_names: { sign_up: 'register', sign_in: 'sign-in', sign_out: 'sign-out' }

  root to: 'static_pages#home'
  
  match '/how-it-works',  to: 'static_pages#how_it_works', as: '/how_it_works'
  match '/who-we-are',    to: 'static_pages#who_we_are', as: '/who_we_are'

  match '/contact',     to: 'contact#contact', via: :get
  match '/contact',     to: 'contact#contact_email', via: :post
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		&copy; 2013 Copyright <%= link_to "Worship Tuner", root_path %> | All Rights Reserved
	</small>
	<nav>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Who We Are", who_we_are_path %></li>
			<li><%= link_to "How it Works", how_it_works_path %></li>
			<li><%= link_to "Song Library", songs_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<nav>
				<ul class="nav">
					<li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
					<li class="<%= 'active' if current_page?(who_we_are_path) %>"><%= link_to "Who We Are", who_we_are_path %></li>
					<li class="<%= 'active' if current_page?(how_it_works_path) %>"><%= link_to "How it Works", how_it_works_path %></li>
					<li class="<%= 'active' if current_page?(songs_path) %>"><%= link_to "Song Library", songs_path %></li>
					<li class="<%= 'active' if current_page?(blog_posts_path) %>"><%= link_to "Blog", blog_posts_path %></li>
					<li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
				</ul>
				<ul class="nav pull-right">
					<li id="fat-menu" class="dropdown">
						<% if user_signed_in? %>
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= "#{current_user.name}" %> <b class="caret"></b></a>
						<% else %>
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Members <b class="caret"></b></a>
						<% end %>
						<ul class="dropdown-menu">
							<% if user_signed_in? %>
								<li><%= link_to "Songs", songs_path %></li>
								<li><%= link_to "Arrangements", song_arrangements_path %></li>
								<li><%= link_to "Attachments", song_arrangement_files_path %></li>
				                <% if current_user.try(:admin?) %>
					                <li class="divider"></li>
									<li><%= link_to "Blog Dashboard", dashboard_blog_posts_path %></li>
				                <% end %>
				                <li class="divider"></li>
								<li><%= link_to "Profile", edit_user_registration_path %></li>
				                <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
			    	        <% else %>
			    	        	<li><%= link_to "Register", new_user_registration_path %></li>
				                <li class="divider"></li>
			    	        	<li><%= link_to "Sign In", new_user_session_path %></li>
			    	        <% end %>
			            </ul>
					</li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<meta name="robots" content="noindex,nofollow">
		<%= stylesheet_link_tag     "application",  media: "all" %>
		<%= javascript_include_tag  "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>    
	</head>
	<body>
		<%= render 'layouts/header' %>
		<section class="top-bar">
			<div class="logo">
				<%= link_to image_tag("logo.png"), root_path %>
			</div>
			<div class="slogan">
				<span class="accent">Community</span> driven <span class="accent">collaborative</span><br />worship chord chart library.
			</div>
		</section>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>